//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ArhitektureV3")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestProject1.ServiceReference1.userType typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestProject1.ServiceReference1.userType type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userType", Namespace="http://schemas.datacontract.org/2004/07/ArhitektureV3")]
    public enum userType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        referent = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        profesor = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        student = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/ArhitektureV3")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idStudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestProject1.ServiceReference1.User userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idStudent {
            get {
                return this.idStudentField;
            }
            set {
                if ((object.ReferenceEquals(this.idStudentField, value) != true)) {
                    this.idStudentField = value;
                    this.RaisePropertyChanged("idStudent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestProject1.ServiceReference1.User user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subject", Namespace="http://schemas.datacontract.org/2004/07/ArhitektureV3")]
    [System.SerializableAttribute()]
    public partial class Subject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestProject1.ServiceReference1.User izvajalecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSubject {
            get {
                return this.idSubjectField;
            }
            set {
                if ((this.idSubjectField.Equals(value) != true)) {
                    this.idSubjectField = value;
                    this.RaisePropertyChanged("idSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestProject1.ServiceReference1.User izvajalec {
            get {
                return this.izvajalecField;
            }
            set {
                if ((object.ReferenceEquals(this.izvajalecField, value) != true)) {
                    this.izvajalecField = value;
                    this.RaisePropertyChanged("izvajalec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        UnitTestProject1.ServiceReference1.User Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.User> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsers", ReplyAction="http://tempuri.org/IService1/GetUsersResponse")]
        UnitTestProject1.ServiceReference1.User[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsers", ReplyAction="http://tempuri.org/IService1/GetUsersResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.User[]> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudents", ReplyAction="http://tempuri.org/IService1/GetStudentsResponse")]
        UnitTestProject1.ServiceReference1.Student[] GetStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudents", ReplyAction="http://tempuri.org/IService1/GetStudentsResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.Student[]> GetStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubjects", ReplyAction="http://tempuri.org/IService1/GetSubjectsResponse")]
        UnitTestProject1.ServiceReference1.Subject[] GetSubjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubjects", ReplyAction="http://tempuri.org/IService1/GetSubjectsResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.Subject[]> GetSubjectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentsFromSubject", ReplyAction="http://tempuri.org/IService1/GetStudentsFromSubjectResponse")]
        UnitTestProject1.ServiceReference1.Student[] GetStudentsFromSubject(int idSubject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentsFromSubject", ReplyAction="http://tempuri.org/IService1/GetStudentsFromSubjectResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.Student[]> GetStudentsFromSubjectAsync(int idSubject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubjectsFromStudent", ReplyAction="http://tempuri.org/IService1/GetSubjectsFromStudentResponse")]
        UnitTestProject1.ServiceReference1.Subject[] GetSubjectsFromStudent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubjectsFromStudent", ReplyAction="http://tempuri.org/IService1/GetSubjectsFromStudentResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.Subject[]> GetSubjectsFromStudentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudent", ReplyAction="http://tempuri.org/IService1/GetStudentResponse")]
        UnitTestProject1.ServiceReference1.Student GetStudent(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudent", ReplyAction="http://tempuri.org/IService1/GetStudentResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.Student> GetStudentAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBiggestSubject", ReplyAction="http://tempuri.org/IService1/GetBiggestSubjectResponse")]
        UnitTestProject1.ServiceReference1.Student GetBiggestSubject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBiggestSubject", ReplyAction="http://tempuri.org/IService1/GetBiggestSubjectResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.Student> GetBiggestSubjectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLongestName", ReplyAction="http://tempuri.org/IService1/GetLongestNameResponse")]
        UnitTestProject1.ServiceReference1.User GetLongestName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLongestName", ReplyAction="http://tempuri.org/IService1/GetLongestNameResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.User> GetLongestNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAverageNameLength", ReplyAction="http://tempuri.org/IService1/GetAverageNameLengthResponse")]
        float GetAverageNameLength();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAverageNameLength", ReplyAction="http://tempuri.org/IService1/GetAverageNameLengthResponse")]
        System.Threading.Tasks.Task<float> GetAverageNameLengthAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStudent", ReplyAction="http://tempuri.org/IService1/AddStudentResponse")]
        int AddStudent(string idStudent, string username, string password, string name, string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStudent", ReplyAction="http://tempuri.org/IService1/AddStudentResponse")]
        System.Threading.Tasks.Task<int> AddStudentAsync(string idStudent, string username, string password, string name, string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSubject", ReplyAction="http://tempuri.org/IService1/AddSubjectResponse")]
        int AddSubject(string subjectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSubject", ReplyAction="http://tempuri.org/IService1/AddSubjectResponse")]
        System.Threading.Tasks.Task<int> AddSubjectAsync(string subjectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        int AddUser(string usernam, string passwor, string name, string surname, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(string usernam, string passwor, string name, string surname, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStudentSubject", ReplyAction="http://tempuri.org/IService1/AddStudentSubjectResponse")]
        int AddStudentSubject(string idStudent, int idSubject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStudentSubject", ReplyAction="http://tempuri.org/IService1/AddStudentSubjectResponse")]
        System.Threading.Tasks.Task<int> AddStudentSubjectAsync(string idStudent, int idSubject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditStudent", ReplyAction="http://tempuri.org/IService1/EditStudentResponse")]
        int EditStudent(string idStudent, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditStudent", ReplyAction="http://tempuri.org/IService1/EditStudentResponse")]
        System.Threading.Tasks.Task<int> EditStudentAsync(string idStudent, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditUser", ReplyAction="http://tempuri.org/IService1/EditUserResponse")]
        int EditUser(int idUser, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditUser", ReplyAction="http://tempuri.org/IService1/EditUserResponse")]
        System.Threading.Tasks.Task<int> EditUserAsync(int idUser, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditSubject", ReplyAction="http://tempuri.org/IService1/EditSubjectResponse")]
        int EditSubject(int idSubject, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditSubject", ReplyAction="http://tempuri.org/IService1/EditSubjectResponse")]
        System.Threading.Tasks.Task<int> EditSubjectAsync(int idSubject, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStudent", ReplyAction="http://tempuri.org/IService1/DeleteStudentResponse")]
        int DeleteStudent(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStudent", ReplyAction="http://tempuri.org/IService1/DeleteStudentResponse")]
        System.Threading.Tasks.Task<int> DeleteStudentAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        int DeleteUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        System.Threading.Tasks.Task<int> DeleteUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSubject", ReplyAction="http://tempuri.org/IService1/DeleteSubjectResponse")]
        int DeleteSubject(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSubject", ReplyAction="http://tempuri.org/IService1/DeleteSubjectResponse")]
        System.Threading.Tasks.Task<int> DeleteSubjectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStudentSubject", ReplyAction="http://tempuri.org/IService1/DeleteStudentSubjectResponse")]
        int DeleteStudentSubject(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStudentSubject", ReplyAction="http://tempuri.org/IService1/DeleteStudentSubjectResponse")]
        System.Threading.Tasks.Task<int> DeleteStudentSubjectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUserToSubject", ReplyAction="http://tempuri.org/IService1/AddUserToSubjectResponse")]
        int AddUserToSubject(int idUser, int idSubject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUserToSubject", ReplyAction="http://tempuri.org/IService1/AddUserToSubjectResponse")]
        System.Threading.Tasks.Task<int> AddUserToSubjectAsync(int idUser, int idSubject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : UnitTestProject1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<UnitTestProject1.ServiceReference1.IService1>, UnitTestProject1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UnitTestProject1.ServiceReference1.User Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.User> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public UnitTestProject1.ServiceReference1.User[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.User[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public UnitTestProject1.ServiceReference1.Student[] GetStudents() {
            return base.Channel.GetStudents();
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.Student[]> GetStudentsAsync() {
            return base.Channel.GetStudentsAsync();
        }
        
        public UnitTestProject1.ServiceReference1.Subject[] GetSubjects() {
            return base.Channel.GetSubjects();
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.Subject[]> GetSubjectsAsync() {
            return base.Channel.GetSubjectsAsync();
        }
        
        public UnitTestProject1.ServiceReference1.Student[] GetStudentsFromSubject(int idSubject) {
            return base.Channel.GetStudentsFromSubject(idSubject);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.Student[]> GetStudentsFromSubjectAsync(int idSubject) {
            return base.Channel.GetStudentsFromSubjectAsync(idSubject);
        }
        
        public UnitTestProject1.ServiceReference1.Subject[] GetSubjectsFromStudent(int id) {
            return base.Channel.GetSubjectsFromStudent(id);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.Subject[]> GetSubjectsFromStudentAsync(int id) {
            return base.Channel.GetSubjectsFromStudentAsync(id);
        }
        
        public UnitTestProject1.ServiceReference1.Student GetStudent(string id) {
            return base.Channel.GetStudent(id);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.Student> GetStudentAsync(string id) {
            return base.Channel.GetStudentAsync(id);
        }
        
        public UnitTestProject1.ServiceReference1.Student GetBiggestSubject() {
            return base.Channel.GetBiggestSubject();
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.Student> GetBiggestSubjectAsync() {
            return base.Channel.GetBiggestSubjectAsync();
        }
        
        public UnitTestProject1.ServiceReference1.User GetLongestName() {
            return base.Channel.GetLongestName();
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.User> GetLongestNameAsync() {
            return base.Channel.GetLongestNameAsync();
        }
        
        public float GetAverageNameLength() {
            return base.Channel.GetAverageNameLength();
        }
        
        public System.Threading.Tasks.Task<float> GetAverageNameLengthAsync() {
            return base.Channel.GetAverageNameLengthAsync();
        }
        
        public int AddStudent(string idStudent, string username, string password, string name, string surname) {
            return base.Channel.AddStudent(idStudent, username, password, name, surname);
        }
        
        public System.Threading.Tasks.Task<int> AddStudentAsync(string idStudent, string username, string password, string name, string surname) {
            return base.Channel.AddStudentAsync(idStudent, username, password, name, surname);
        }
        
        public int AddSubject(string subjectName) {
            return base.Channel.AddSubject(subjectName);
        }
        
        public System.Threading.Tasks.Task<int> AddSubjectAsync(string subjectName) {
            return base.Channel.AddSubjectAsync(subjectName);
        }
        
        public int AddUser(string usernam, string passwor, string name, string surname, string type) {
            return base.Channel.AddUser(usernam, passwor, name, surname, type);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(string usernam, string passwor, string name, string surname, string type) {
            return base.Channel.AddUserAsync(usernam, passwor, name, surname, type);
        }
        
        public int AddStudentSubject(string idStudent, int idSubject) {
            return base.Channel.AddStudentSubject(idStudent, idSubject);
        }
        
        public System.Threading.Tasks.Task<int> AddStudentSubjectAsync(string idStudent, int idSubject) {
            return base.Channel.AddStudentSubjectAsync(idStudent, idSubject);
        }
        
        public int EditStudent(string idStudent, string name) {
            return base.Channel.EditStudent(idStudent, name);
        }
        
        public System.Threading.Tasks.Task<int> EditStudentAsync(string idStudent, string name) {
            return base.Channel.EditStudentAsync(idStudent, name);
        }
        
        public int EditUser(int idUser, string name) {
            return base.Channel.EditUser(idUser, name);
        }
        
        public System.Threading.Tasks.Task<int> EditUserAsync(int idUser, string name) {
            return base.Channel.EditUserAsync(idUser, name);
        }
        
        public int EditSubject(int idSubject, string name) {
            return base.Channel.EditSubject(idSubject, name);
        }
        
        public System.Threading.Tasks.Task<int> EditSubjectAsync(int idSubject, string name) {
            return base.Channel.EditSubjectAsync(idSubject, name);
        }
        
        public int DeleteStudent(string id) {
            return base.Channel.DeleteStudent(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteStudentAsync(string id) {
            return base.Channel.DeleteStudentAsync(id);
        }
        
        public int DeleteUser(int id) {
            return base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteUserAsync(int id) {
            return base.Channel.DeleteUserAsync(id);
        }
        
        public int DeleteSubject(int id) {
            return base.Channel.DeleteSubject(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteSubjectAsync(int id) {
            return base.Channel.DeleteSubjectAsync(id);
        }
        
        public int DeleteStudentSubject(int id) {
            return base.Channel.DeleteStudentSubject(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteStudentSubjectAsync(int id) {
            return base.Channel.DeleteStudentSubjectAsync(id);
        }
        
        public int AddUserToSubject(int idUser, int idSubject) {
            return base.Channel.AddUserToSubject(idUser, idSubject);
        }
        
        public System.Threading.Tasks.Task<int> AddUserToSubjectAsync(int idUser, int idSubject) {
            return base.Channel.AddUserToSubjectAsync(idUser, idSubject);
        }
    }
}
